# Generated by Django 5.1.7 on 2025-03-10 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='name')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('barcode', models.CharField(max_length=256, unique=True, verbose_name='barcode')),
                ('stock', models.IntegerField(default=0, verbose_name='stock')),
                ('inserted_at', models.DateTimeField(auto_now_add=True, verbose_name='inserted_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
